# Generated by Django 2.1.2 on 2019-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortener',
            fields=[
                ('url_shortener_id', models.IntegerField(primary_key=True, serialize=False)),
                ('absolute_url', models.TextField()),
                ('short_url', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
