# Generated by Django 2.1.2 on 2019-01-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='url_shortener_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
